package day2;
public class product {
String name;
int price;
int quantity;
double discount;
double gst;
public static void main(String[] args) {
	product p1 = new product();
	p1.name = "watch";
	p1.price= 15000;
	p1.quantity=5;
	p1.discount = 5;
	p1.gst= 5;
	System.out.println("The name of product is :"+p1.name);
	System.out.println("The price of product is :"+p1.price);
	System.out.println("The quantity of product is :"+p1.quantity);
	System.out.println("The discount of product is :"+p1.discount+"%");
	System.out.println("The gst of product is :"+p1.gst+"%");
	product p2 = new product();
	p2.name = "ring";
	p2.price= 15000;
	p2.quantity=6;
	p2.discount = 6;
	p2.gst= 5;
	System.out.println("The name of product is :"+p2.name);
	System.out.println("The price of product is :"+p2.price);
	System.out.println("The quantity of product is :"+p2.quantity);
	System.out.println("The discount of product is :"+p2.discount+"%");
	System.out.println("The gst of product is :"+p2.gst+"%");
	product p3 = new product();
	p3.name = "handbag";
	p3.price= 15000;
	p3.quantity=5;
	p3.discount = 5;
	p3.gst= 5;
	System.out.println("The name of product is :"+p3.name);
	System.out.println("The price of product is :"+p3.price);
	System.out.println("The quantity of product is :"+p3.quantity);
	System.out.println("The discount of product is :"+p3.discount+"%");
	System.out.println("The gst of product is :"+p3.gst+"%");
	product p4 = new product();
	p4.name = "slippers";
	p4.price= 15000;
	p4.quantity=5;
	p4.discount = 5;
	p4.gst= 5;
	System.out.println("The name of product is :"+p4.name);
	System.out.println("The price of product is :"+p4.price);
	System.out.println("The quantity of product is :"+p4.quantity);
	System.out.println("The discount of product is :"+p4.discount+"%");
	System.out.println("The gst of product is :"+p4.gst+"%");
	product p5 = new product();
	p5.name = "jewellery";
	p5.price= 15000;
	p5.quantity=5;
	p5.discount = 5;
	p5.gst= 5;
	System.out.println("The name of product is :"+p5.name);
	System.out.println("The price of product is :"+p5.price);
	System.out.println("The quantity of product is :"+p5.quantity);
	System.out.println("The discount of product is :"+p5.discount+"%");
	System.out.println("The gst of product is :"+p5.gst+"%");	
}
}
